### ISSUE TITLE
Feature request: Transactional OpenMlsProvider

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#314]
### Is your feature request related to a problem?

When working with the `XmtpOpenMlsProvider` inside a transaction (for example, when processing an inbound message) it is awkward that the `SqlKeyStore` is not able to accept a `DbConnection` to handle writes within the transaction.

In some cases, I believe this will lead to a deadlock because of SQLite's inability to handle concurrent writes.

Ideally, we would be able to create a new instance of XmtpOpenMlsProvider with a `SqlKeystore` scoped to the transaction's `DbConnection`. This is made challenging by the fact that the `OpenMlsProvider` trait requires that implementations be `Send + Sync`, which a DbConnection is not. We'll have to figure out some sort of creative solution here.

**Comment by richardhuaaa** [comment]
@neekolas, do you have a more specific example of when things might break if the `SqlKeyStore` is not operating within a transaction? Is it specifically the issue of deadlocks, or are we worried about data inconsistency? If the latter, what exactly - are we worried that cryptographic keys will be deleted in some cases, but the corresponding decrypted message doesn’t end up getting stored? That might help us come up with a clearer solution

**Comment by neekolas** [comment]
It's data inconsistency. It's going to be tough to avoid doing anything that might necessitate a rollback after decrypting a message. Deadlocks are a suspicion, but I guess we'll find out once we start implementing the state machine.

**Comment by insipx** [comment]
We can't really fight our way around the borrow checker w/o using unsafe, so our only option here, if we want to continue with one Connection from the transaction, is probably refactoring SqlKeyStore/XmtpOpenMlsProvider with one `Connection` wrapped in a mutex. The issue here is `SqliteConnection` is not Sync/intended to be used in a single-threaded context. `Pool` is Sync, but iiuc from what you're saying we may face race conditions since this is going to hand out multiple connections which we definitely don't want inside of a transaction. 

The only other solution would be to touch code in `OpenMls` itself and relax the Sync bound on the `OpenMlsProvider` trait. Depending on if this is a requirement from an audit or not, could be another way forward, but I think it's fairly intentional here to make sure that stores and deletes are atomic.

I think the way forward here will be refactoring SqlKeyStore around a Mutex<Connection>, and providing a nice wrapper API in EncryptedKeyStore for transactions specific to what we're doing. Then we can refactor XmtpOpenMlsProvider around that same connection.

Q: Do we expect to mostly read or write from the store, or are they about equal? We could optimize with RWLock and hand out multiple read references if we need to

**Comment by neekolas** [comment]
> Q: Do we expect to mostly read or write from the store, or are they about equal? We could optimize with RWLock and hand out multiple read references if we need to

From what I've seen it's close to equal. Maybe 70% read 30% write. A lot of common operations are to read a value and then delete it, with a few things that get read but never deleted.

Another Q: Will we always be operating within a transaction, or is it worth creating another SqlKeyStore impl that has a connection behind this mutex?

I think we can assume that we'll either be operating inside a transaction or inside a function that already has an open `DbConnection` that could be used the same way.


My feeling is that concurrent accesses inside the KeyStore should be very rare. Operations are quick and we aren't building a server handling hundreds of parallel requests. Every transaction would be used in one request/thread, so if each transaction has its own `SqlKeyStore` with its own mutex we shouldn't ever experience lock contention in practice.

**Comment by richardhuaaa** [comment]
Can we have the keystore always use the same DB connection, and start and close transactions outside of OpenMLS on that connection whenever we are doing an atomic operation? That saves us having to re-create it every time and doesn't rely on any assumptions about OpenMLS, as well as being simpler to reason about.

**Comment by neekolas** [comment]
> That saves us having to re-create the keystore every time and doesn't rely on any assumptions about OpenMLS, as well as being simpler to reason about.

I'm not losing sleep about re-creating the keystore every time. It's basically just instantiating a new struct and copying some pointers. That feels pretty close to free. Re-creating RustCrypto is maybe a little more expensive, since you have to initiate a new RNG. But we could probably optimize that part out.

The part of the DevEx I worry about there is accidentally bringing unrelated operations into the transaction if we have concurrent jobs happening. That feels harder to reason about.

**Comment by insipx** [comment]
This is actually a more difficult issue than I initially thought, after spending some time on it

- the limitation of SQLite connection as `!Sync` is a limitation of SQLIte. there is an SQLite mode for serialized reads/writes which we could enable, but all that does is use an internal SQLite mutex. This is an issue [other db libraries also face](https://github.com/launchbadge/sqlx/issues/920)
- We can't use `RwLock` because `RwLock` does not give use Sync if the inner `T` is not also `Sync`. Anyway, it wouldn't be safe w.r.t concurency
- We can't just wrap DbConnection in a Mutex either, because diesels transaction requires `&mut Connection`, so it has to be unwrapped before starting the connection, which just takes us back to the original issue

I've been thinking about this in the context of the overall design w.r.t other issues #292 and [Nicks comment about traits](https://github.com/xmtp/libxmtp/pull/323#discussion_r1387493790) as well

 

I think there are a couple ways forward, some more extreme than others
1.) enable SQLite Serialized mode. This is probably the easiest and fastest, although we lost lots of control and i can't speak to how diesel manages Database configuration w.r.t. Connections, so we may have to manually unsafe impl Sync on the connection if we enable this

2.) Create our own TransactionManager /TransactionOverlay and defer committing to the database once we've gathered all the data we need. We could refactor traits to make the API easier as well. This would give us the most control over strict ordering of database information to commit.

It would consist of:
Create a generic `TransactionOverlay` in place of diesels transaction. We would need methods:
- commit
- rollback
- begin

`TransactionOverlay` acts as a proxy to our DatabaseConnection here. It will be totally Send + Sync, and internally just store a ordered list of updates to the database behind a Mutex or whatever synchronization primitive we want. It needs to implement `Store`/`Fetch`/`Delete`. On commit, it opens an SQLite transaction after grabbing a Connection from the pool (which is Send + Sync) and does the update.

EncryptedMessageStore can have it's own transaction wrapper callback that replaces a diesel `&mut Connection` with this TransactionOverlay, so from the outside transactions will look essentially the same.

Our design of the traits can change from implementing on the DbConnection, to accepting a DbConnection. This solves the syntax creep that @neekolas is experiencing with the `Delete` trait. Instead of implementing on Connection, we just refactor to accept a Connection like Store. We then make use of diesels [`Identifiable`](https://docs.rs/diesel/2.1.3/diesel/associations/trait.Identifiable.html) trait to remove the need for an associated type in those traits (EX: `<StoredGroupMessage as Identifiable>::Id`). This lets us keep the macros as relatively unchanged as well.

3.) The most extreme would be to replace diesel with sqlx, which has a different Transaction philosophy, but which essentially does what I describe in Option 2. There is a transaction object, Send + Sync which may be passed around. The big benefit to this would be w.r.t #292 -- it's async by default, so we wouldn't have to worry about blocking our network requests. This option, however, introduces much more async complexity, and we would be rewriting a large portion of the already existent storage code so  more development hours would be spent on that

---

In the interest of time I think Option 2 is the best, and don't think it would take away too many development hours for our goal of the statement done by Thanksgiving

**Comment by neekolas** [comment]
I think I'd have to get into the details of how the `TransactionOverlay` would work.

This part is what gives me pause

> On commit, it opens an SQLite transaction after grabbing a Connection from the pool (which is Send + Sync) and does the update.

If we are passing this into `openmls`, they likely have expectations that a delete or update is represented in the database immediately and we could change the behaviour of their code if those changes have not yet been applied. We can change our own code to avoid those assumptions, but it's a much hairier task to make sure they aren't.

**Comment by neekolas** [comment]
@insipx @richardhuaaa 

I decided to take a look at how [Wire App](https://github.com/wireapp/core-crypto/blob/develop/keystore/src/mls.rs) handles database connections in their Mls keystore. 
```rust
impl openmls_traits::key_store::OpenMlsKeyStore for crate::connection::Connection { ... }
```

They just implemented the KeyStore interface on the connection itself, which is nice and tidy. Of course, the connection still needs to be `Send + Sync`. They have wrappers [here](https://github.com/wireapp/core-crypto/blob/develop/keystore/src/connection/mod.rs#L81) that use Arcs and Mutexes to handle concurrent access and then they can safely add:
```rust
unsafe impl Send for Connection {}
unsafe impl Sync for Connection {}
```

I believe they are then able to do option 1 without needing to use Serialized mode, although maybe they are doing both and I just haven't found the place where they enable it.

**Comment by insipx** [comment]
This seems like a much simpler solution

One thing I did find interesting on a second glance, at the very least we can definitely do something similar with our connection. I'll have to look into R2D2 pooling, since I think they probably use some synchronization primitives on their own on the Pool, but I'll try to prototype this and see what I come back with

**Comment by insipx** [comment]
Actually got confirmation from an openmls dev that the Send + Sync requirement on OpenMlsProvider should have been relaxed already [here](https://openmls.zulipchat.com/#narrow/stream/262730-general/topic/MlsProvider.2FKeyStore/near/401440854) so I'll make a PR in openmls to fix that, which means we don't have to do any workarounds
