### ISSUE TITLE
Drop DB connection sometimes fails to drop

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#932]
It appears that occasionally in converse after calling `dropLocalDatabaseConnection` that the connection is still present and crashes can occur this is rare but still happens. 

Unrelated but `deleteLocalDatabase` does not drop the database connection so connections can still be present even after a database was deleted. We should proof this by either dropping the database connection in the delete function or something else.

**Comment by insipx** [comment]
Could be a quirk with react-native or something that is delaying the actual drop occurring in libxmtp. `sqlite3_close` is directly called by Diesel `Drop` implementation, so it should drop reliably from rust.

One thing preventing the drop could be the RwLock is still blocking and not unlocking in time, in which case we can [force a fair unlock](https://docs.rs/parking_lot/latest/parking_lot/type.RwLockWriteGuard.html#method.unlock_fair)

Otherwise, this issue maybe tangentially related: https://stackoverflow.com/questions/8511901/system-data-sqlite-close-not-releasing-database-file it's C#, but maybe the same thing is happening with react native. not too familiar with RN side but maybe there's some reference that's being held onto that will run rusts destructor in the future across the FFI boundary.
