### ISSUE TITLE
Revoke Installations

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#974]

**Comment by neekolas** [comment]
I'm happy to take the libxmtp and bindings side of this. Should be easy, since it's already supported in `xmtp_id` and is just another type of identity update.

Will need support getting it plumbed through to RN.

To actually do the revocation in an app like Converse you would need to sign a signature request and then pass it back in to the SDK.

**Comment by nplasterer** [comment]
Since I'm deep in the add wallet work right now I can take the SDK side if you get libxmtp setup. I could also probably help with bindings as well.

**Comment by nplasterer** [comment]
@neekolas to confirm this work Scott did here isn't related? https://github.com/xmtp/libxmtp/pull/889/files#diff-3a24c3e76565487a710ac9863ac05160128f4f90892e07849b555a6de43a6e8fR363-R377
